	package model;
	import java.sql.SQLException;
	import java.util.Properties;

	import com.mysql.jdbc.Connection;
	import com.mysql.jdbc.Driver;
	public class Connect {
		private static String strServer = "localhost";
		private static String strDatabase = "huyentrang";
		private static String strUser = "huyentrang";
		private static String strPwd = "123456789";

		public static Connection getConnect() {
			Connection conn = null;
			String strConnect = "jdbc:mysql://" + strServer + "/" + strDatabase
					+ "?useUnicode=true&characterEncoding=utf-8";
			Properties pro = new Properties();
			pro.put("user", strUser);
			pro.put("password", strPwd);
			try {
				com.mysql.jdbc.Driver driver = new Driver();
				conn = (Connection) driver.connect(strConnect, pro);
			} catch (SQLException ex) {
				System.err.println("Kết nối Database thất bại!");
				// ex.printStackTrace();
			}
			return conn;
		}
	}

